### ISSUE TITLE
link tag at the top of elements 

### ISSUE THREAD

**Issue by thomasjfox1** [NathanMarq/polymer-scaffold#1]
According to the docs, you need `<link rel="import" href="../bower_components/polymer/polymer.html">` at the top of each custom element's html file (or whatever path it is).

**Comment by NathanMarq** [comment]
@thomasjfox1, it isn't necessary to link in the polymer element to every custom element you're using. I opted for just including it once in the index.html (after vulcanizing it), then concatenating, vulcanizing, and including all the custom elements and their dependencies. This should all be happening with the grunt build process.

Is the application not working for you this way?

**Comment by thomasjfox1** [comment]
@NathanMarq ah, I see the grunt now. Makes sense. Good setup here.
